# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_auto_20170823_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
